### ISSUE TITLE
Direct transport: concurrent map read and map write

### ISSUE THREAD

**Issue by ronnno** [orbs-network/orbs-network-go#1218]
**Describe the bug**

Direct transport panics on concurrent map read and map write in `direct_transport.go:111`

**Steps To Reproduce**

Flakiness in e2e tests

**Logs**

```
fatal error: concurrent map read and map write

goroutine 89 [running]:
runtime.throw(0x4906c9f, 0x21)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc0004d4e98 sp=0xc0004d4e68 pc=0x402ecd2
runtime.mapaccess1_faststr(0x47dff80, 0xc000711350, 0xc0001fb6e0, 0x14, 0xc000a68d30)
	/usr/local/go/src/runtime/map_faststr.go:21 +0x469 fp=0xc0004d4f08 sp=0xc0004d4e98 pc=0x4013ea9
github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp.(*DirectTransport).connect.func1()
	/Users/ron/work/src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp/direct_transport.go:111 +0x67 fp=0xc0004d4f58 sp=0xc0004d4f08 pc=0x4666907
github.com/orbs-network/orbs-network-go/synchronization/supervised.tryOnce(0x5748070, 0xc0000bd6e0, 0xc0007113b0)
	/Users/ron/work/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:60 +0x57 fp=0xc0004d4f88 sp=0xc0004d4f58 pc=0x447fdf7
github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever.func1(0xc0001a4c60, 0x5748070, 0xc0000bd6e0, 0xc0007113b0, 0x4a6e440, 0xc0000aa1c0)
	/Users/ron/work/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:41 +0x69 fp=0xc0004d4fb0 sp=0xc0004d4f88 pc=0x4480789
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0004d4fb8 sp=0xc0004d4fb0 pc=0x405f081
created by github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever
	/Users/ron/work/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37 +0x8e
```

**Environment:**

local dev env e2e tests

**Comment by ronnno** [comment]
fixed a while ago
