### ISSUE TITLE
StartGammaServer fails on bind: address already in use

### ISSUE THREAD

**Issue by itamararjuan** [orbs-network/orbs-network-go#1272]
Tried running Gamma's E2E tests and this happened:

```
info 2019-08-11T09:16:54.577916Z finished creating development network function=gamma.StartGammaServer source=bootstrap/gamma/server.go:60 
info 2019-08-11T09:16:54.577947Z processor executing contract node=a32884 service=processor-native entry-point=BenchmarkConsensus.Tick request-id=BenchmarkConsensus.Tick-1565515014577805917 contract=_GlobalPreOrder method=approve function=native.(*service).ProcessCall source=services/processor/native/service.go:111 
panic: failed to start http server: listen tcp :35222: bind: address already in use

goroutine 552 [running]:
github.com/orbs-network/orbs-network-go/bootstrap/httpserver.NewHttpServer(0x12a6aa0, 0xc0031da6e0, 0x12be040, 0xc00269a360, 0x12bc140, 0xc002a920c0, 0x12beac0, 0xc00266c540, 0xc002662e60, 0x6)
	/home/circleci/.go_workspace/src/github.com/orbs-network/orbs-network-go/bootstrap/httpserver/server.go:83 +0x63b
github.com/orbs-network/orbs-network-go/bootstrap/gamma.StartGammaServer(0xc000d9ff70, 0x6, 0x0, 0x1162c98, 0x36, 0x0, 0x6)
	/home/circleci/.go_workspace/src/github.com/orbs-network/orbs-network-go/bootstrap/gamma/server.go:62 +0x27b
github.com/orbs-network/orbs-network-go/bootstrap/gamma.Main()
	/home/circleci/.go_workspace/src/github.com/orbs-network/orbs-network-go/bootstrap/gamma/server.go:98 +0x21c
created by github.com/orbs-network/orbs-network-go/bootstrap/gamma.RunMain
	/home/circleci/.go_workspace/src/github.com/orbs-network/orbs-network-go/bootstrap/gamma/test_kit.go:14 +0x1b5
FAIL	github.com/orbs-network/orbs-network-go/bootstrap/gamma/e2e	12.882s
Exited with code 1
```

How does the Gamma Server chooses it's tcp port before launching ? I assume if it's random that it checked prior to picking it ?

**Comment by electricmonk** [comment]
gamma now binds to port 0 in tests, meaning that it'll choose a truly random port
