### ISSUE TITLE
TestPeriodicalTriggerKeepsGoingOnPanic hangs

### ISSUE THREAD

**Issue by electricmonk** [orbs-network/orbs-network-go#1282]
```
=== RUN   TestPeriodicalTriggerKeepsGoingOnPanic
scvg0: inuse: 1, idle: 61, sys: 63, released: 0, consumed: 63 (MB)
scvg1: 61 MB released
scvg1: inuse: 1, idle: 61, sys: 63, released: 61, consumed: 1 (MB)
scvg2: inuse: 1, idle: 61, sys: 63, released: 61, consumed: 1 (MB)
scvg3: inuse: 1, idle: 61, sys: 63, released: 61, consumed: 1 (MB)
scvg4: inuse: 1, idle: 61, sys: 63, released: 61, consumed: 1 (MB)
scvg5: inuse: 1, idle: 61, sys: 63, released: 61, consumed: 1 (MB)
scvg6: inuse: 1, idle: 61, sys: 63, released: 61, consumed: 1 (MB)
scvg7: inuse: 1, idle: 61, sys: 63, released: 61, consumed: 1 (MB)
panic: test timed out after 20m0s

goroutine 72 [running]:
testing.(*M).startAlarm.func1()
        /usr/local/go/src/testing/testing.go:1296 +0x13a
created by time.goFunc
        /usr/local/go/src/time/sleep.go:172 +0x52

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000134300, 0xa23f27, 0x26, 0xa2f148, 0xc0000f7c01)
        /usr/local/go/src/testing/testing.go:879 +0x692
testing.runTests.func1(0xc000134300)
        /usr/local/go/src/testing/testing.go:1119 +0xa9
testing.tRunner(0xc000134300, 0xc0000f7d88)
        /usr/local/go/src/testing/testing.go:827 +0x163
testing.runTests(0xc00000c8e0, 0xf9dbc0, 0x15, 0x15, 0xc000092ff0)
        /usr/local/go/src/testing/testing.go:1117 +0x4ef
testing.(*M).Run(0xc000132180, 0x0)
        /usr/local/go/src/testing/testing.go:1034 +0x2ef
main.main()
        _testmain.go:84 +0x222

goroutine 5 [syscall]:
os/signal.signal_recv(0x46f0c1)
        /usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x30
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x4f

goroutine 60 [chan receive]:
github.com/orbs-network/orbs-network-go/synchronization.(*PeriodicalTrigger).Stop(0xc0001c6280)
        /go/src/github.com/orbs-network/orbs-network-go/synchronization/trigger.go:78 +0x7a
github.com/orbs-network/orbs-network-go/synchronization_test.TestPeriodicalTriggerKeepsGoingOnPanic(0xc0001c4400)
        /go/src/github.com/orbs-network/orbs-network-go/synchronization/trigger_test.go:178 +0x1e9
testing.tRunner(0xc0001c4400, 0xa2f148)
        /usr/local/go/src/testing/testing.go:827 +0x163
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:878 +0x65a
FAIL    github.com/orbs-network/orbs-network-go/synchronization 1200.311s
```

**Comment by electricmonk** [comment]
@ronnno did you fix this one?
