### ISSUE TITLE
Process crashes on concurrent map read and write

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#1285]
Version: v1.1.1

```
fatal error: concurrent map read and map write

goroutine 9 [running]:
runtime.throw(0xf6e285, 0x21)
	/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc000205e98 sp=0xc000205e68 pc=0x793e92
runtime.mapaccess1_faststr(0xe61dc0, 0xc001d76ba0, 0xc0001f9ea0, 0x14, 0xc001720030)
	/usr/local/go/src/runtime/map_faststr.go:21 +0x418 fp=0xc000205f08 sp=0xc000205e98 pc=0x779ce8
github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp.(*DirectTransport).connect.func1()
	/go/src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp/direct_transport.go:111 +0x67 fp=0xc000205f58 sp=0xc000205f08 pc=0xd07c17
github.com/orbs-network/orbs-network-go/synchronization/supervised.tryOnce(0x7fe5429a8c38, 0xc0001603c0, 0xc001d76c00)
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:60 +0x57 fp=0xc000205f88 sp=0xc000205f58 pc=0xb25c37
github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever.func1(0xc0001764e0, 0x7fe5429a8c38, 0xc0001603c0, 0xc001d76c00, 0x1068900, 0xc0001584c0)
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:41 +0x69 fp=0xc000205fb0 sp=0xc000205f88 pc=0xb26629
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000205fb8 sp=0xc000205fb0 pc=0x7c4e51
created by github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37 +0x8e

goroutine 1 [runnable]:
github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp.NewTransportQueue(0x1400000, 0x3e8, 0x7fe542c60890, 0xc000158500, 0xc000158500)
	/go/src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp/queue.go:35 +0x55
github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp.(*DirectTransport).connect(0xc0007428c0, 0x1068900, 0xc0001584c0, 0xc0001f9d20, 0x14, 0x105e680, 0xc000248060)
	/go/src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp/direct_transport.go:104 +0xc5
github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp.NewDirectTransport(0x1068900, 0xc0001584c0, 0x7fe5429a8bf0, 0xc000189110, 0x106d180, 0xc00014c9c0, 0x106d400, 0xc000158500, 0x106bb80)
	/go/src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp/direct_transport.go:93 +0x30e
github.com/orbs-network/orbs-network-go/bootstrap.NewNode(0x7fe542c60640, 0xc000189110, 0x106d180, 0xc00014c960, 0xc000189110, 0x106d180)
	/go/src/github.com/orbs-network/orbs-network-go/bootstrap/node.go:53 +0x3ca
main.main()
	/go/src/github.com/orbs-network/orbs-network-go/main.go:42 +0x2c5

goroutine 19 [chan receive, 2 minutes]:
github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc00014c2a0, 0xc00014c1e0)
	/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:36 +0xb6
created by github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
	/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:29 +0xdc

goroutine 20 [chan receive, 2 minutes]:
github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc00014c2a0, 0xc00014c240)
	/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:81 +0x7b
created by github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
	/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:30 +0x108

goroutine 21 [chan receive]:
github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/metrics.(*meterArbiter).tick(0x17ccde0)
	/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/metrics/meter.go:289 +0x78
created by github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/metrics.NewMeterForced
	/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/metrics/meter.go:70 +0xfd

goroutine 22 [select]:
github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/consensus/ethash.(*Ethash).remote(0xc0001ec000, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/consensus/ethash/sealer.go:307 +0x526
created by github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/consensus/ethash.New
	/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:496 +0x340

goroutine 23 [chan receive, 2 minutes]:
github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000150bb0)
	/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x9c
created by github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 24 [chan receive, 2 minutes]:
github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000150bb0)
	/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x9c
created by github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 25 [chan receive, 2 minutes]:
github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000150bb0)
	/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x9c
created by github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 26 [chan receive, 2 minutes]:
github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc000150bb0)
	/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core/tx_cacher.go:63 +0x9c
created by github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core.newTxSenderCacher
	/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/ethereum/go-ethereum/core/tx_cacher.go:55 +0x9f

goroutine 27 [syscall, 2 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 28 [chan receive, 2 minutes]:
github.com/orbs-network/orbs-network-go/services/blockstorage/adapter/filesystem.closeOnContextDone.func1(0x1068900, 0xc0001584c0, 0xc0001520c8, 0x106d180, 0xc00014ca20)
	/go/src/github.com/orbs-network/orbs-network-go/services/blockstorage/adapter/filesystem/file_system_persistence.go:191 +0x4c
created by github.com/orbs-network/orbs-network-go/services/blockstorage/adapter/filesystem.closeOnContextDone
	/go/src/github.com/orbs-network/orbs-network-go/services/blockstorage/adapter/filesystem/file_system_persistence.go:190 +0x67

goroutine 8 [runnable]:
syscall.Close(0x6, 0x1, 0x6)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:309 +0xcc
net.(*ipStackCapabilities).probe(0x17f5090)
	/usr/local/go/src/net/ipsock_posix.go:31 +0x362
net.(*ipStackCapabilities).probe-fm()
	/usr/local/go/src/net/ipsock.go:31 +0x2a
sync.(*Once).Do(0x17f5090, 0xc00005dae0)
	/usr/local/go/src/sync/once.go:44 +0xb3
net.supportsIPv4map(0xc0034c8000)
	/usr/local/go/src/net/ipsock.go:46 +0x57
net.favoriteAddrFamily(0xf57047, 0x3, 0x106b160, 0xc0034c8000, 0x0, 0x0, 0xf59023, 0x6, 0x8, 0x0)
	/usr/local/go/src/net/ipsock_posix.go:120 +0x88
net.internetSocket(0x1068940, 0xc000038028, 0xf57047, 0x3, 0x106b160, 0xc0034c8000, 0x0, 0x0, 0x1, 0x0, ...)
	/usr/local/go/src/net/ipsock_posix.go:140 +0x9b
net.(*sysListener).listenTCP(0xc00005dcf0, 0x1068940, 0xc000038028, 0xc0034c8000, 0x105fd00, 0xc0034c8000, 0x3)
	/usr/local/go/src/net/tcpsock_posix.go:159 +0xb7
net.(*ListenConfig).Listen(0xc00005dd80, 0x1068940, 0xc000038028, 0xf57047, 0x3, 0xc0034a0010, 0x5, 0xc0034a0010, 0x5, 0x5, ...)
	/usr/local/go/src/net/dial.go:604 +0x56e
net.Listen(0xf57047, 0x3, 0xc0034a0010, 0x5, 0x1, 0xc0034a0010, 0x5, 0x0)
	/usr/local/go/src/net/dial.go:674 +0x7e
github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp.(*DirectTransport).serverListenForIncomingConnections(0xc0007428c0, 0x1068900, 0xc0001584c0, 0x1130, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp/direct_incoming.go:24 +0xcc
github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp.(*DirectTransport).serverMainLoop(0xc0007428c0, 0x1068900, 0xc0001584c0, 0xc001dd1130)
	/go/src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp/direct_incoming.go:53 +0x67
github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp.NewDirectTransport.func1()
	/go/src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp/direct_transport.go:87 +0x75
github.com/orbs-network/orbs-network-go/synchronization/supervised.tryOnce(0x7fe5429a8c38, 0xc0001603c0, 0xc00138b400)
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:60 +0x57
github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever.func1(0xc000176480, 0x7fe5429a8c38, 0xc0001603c0, 0xc00138b400, 0x1068900, 0xc0001584c0)
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:41 +0x69
created by github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37 +0x8e

goroutine 10 [runnable]:
fmt.Sprintf(0xf57921, 0x5, 0xc0034c3e28, 0x2, 0x2, 0x8342a0, 0x1783710)
	/usr/local/go/src/fmt/print.go:201 +0xdd
github.com/orbs-network/orbs-network-go/instrumentation/trace.NewContext(0x1068900, 0xc0001584c0, 0xc001f86000, 0x2f, 0x1, 0xc001f86000)
	/go/src/github.com/orbs-network/orbs-network-go/instrumentation/trace/context.go:32 +0x168
github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp.(*DirectTransport).clientMainLoop(0xc0007428c0, 0x1068900, 0xc0001584c0, 0xc000174280)
	/go/src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp/direct_outgoing.go:23 +0xe1
github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp.(*DirectTransport).connect.func1()
	/go/src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/tcp/direct_transport.go:111 +0x96
github.com/orbs-network/orbs-network-go/synchronization/supervised.tryOnce(0x7fe5429a8c38, 0xc0001603c0, 0xc001d76c30)
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:60 +0x57
github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever.func1(0xc000176540, 0x7fe5429a8c38, 0xc0001603c0, 0xc001d76c30, 0x1068900, 0xc0001584c0)
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:41 +0x69
created by github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37 +0x8e

goroutine 11 [runnable]:
github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever.func1(0xc0001765a0, 0x7fe5429a8c38, 0xc0001603c0, 0xc001d76c60, 0x1068900, 0xc0001584c0)
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37
created by github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37 +0x8e

goroutine 12 [runnable]:
github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever.func1(0xc000176600, 0x7fe5429a8c38, 0xc0001603c0, 0xc001d76c90, 0x1068900, 0xc0001584c0)
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37
created by github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37 +0x8e

goroutine 13 [runnable]:
github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever.func1(0xc000176660, 0x7fe5429a8c38, 0xc0001603c0, 0xc001d76cc0, 0x1068900, 0xc0001584c0)
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37
created by github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37 +0x8e

goroutine 14 [runnable]:
github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever.func1(0xc0001766c0, 0x7fe5429a8c38, 0xc0001603c0, 0xc001d76cf0, 0x1068900, 0xc0001584c0)
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37
created by github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37 +0x8e

goroutine 15 [runnable]:
github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever.func1(0xc000176720, 0x7fe5429a8c38, 0xc0001603c0, 0xc001d76d20, 0x1068900, 0xc0001584c0)
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37
created by github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37 +0x8e

goroutine 16 [runnable]:
github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever.func1(0xc000176780, 0x7fe5429a8c38, 0xc0001603c0, 0xc001d76d50, 0x1068900, 0xc0001584c0)
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37
created by github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37 +0x8e

goroutine 50 [runnable]:
github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever.func1(0xc0001767e0, 0x7fe5429a8c38, 0xc0001603c0, 0xc001d76d80, 0x1068900, 0xc0001584c0)
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37
created by github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37 +0x8e

goroutine 51 [runnable]:
github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever.func1(0xc000176840, 0x7fe5429a8c38, 0xc0001603c0, 0xc001d76db0, 0x1068900, 0xc0001584c0)
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37
created by github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37 +0x8e

goroutine 52 [runnable]:
github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever.func1(0xc0001768a0, 0x7fe5429a8c38, 0xc0001603c0, 0xc001d76de0, 0x1068900, 0xc0001584c0)
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37
created by github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever
	/go/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:37 +0x8e
```

**Comment by electricmonk** [comment]
already fixed in master
