### ISSUE TITLE
TestPeriodicalTriggerKeepsGoingOnPanic Deadlock

### ISSUE THREAD

**Issue by ronnno** [orbs-network/orbs-network-go#1339]
```
goroutine 73 [chan receive]:
github.com/orbs-network/orbs-network-go/synchronization.(*PeriodicalTrigger).Stop(...)
	/home/circleci/project/synchronization/trigger.go:68
github.com/orbs-network/orbs-network-go/synchronization_test.TestPeriodicalTriggerKeepsGoingOnPanic.func1(0x8e9200, 0xc0001ba380, 0xc0001c8230)
	/home/circleci/project/synchronization/trigger_test.go:154 +0x1af
github.com/orbs-network/orbs-network-go/test.WithConcurrencyHarness(0x8ed1c0, 0xc0001c0400, 0xc00019cf88)
	/home/circleci/project/test/concurrency.go:37 +0x2c9
github.com/orbs-network/orbs-network-go/synchronization_test.TestPeriodicalTriggerKeepsGoingOnPanic(0xc0001c0400)
	/home/circleci/project/synchronization/trigger_test.go:140 +0x5a
testing.tRunner(0xc0001c0400, 0x8797a8)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x35a

goroutine 74 [chan send]:
github.com/orbs-network/orbs-network-go/synchronization_test.(*collector).Error(0xc0001ca008, 0x864236, 0xf, 0xc000011180, 0x3, 0x3)
	/home/circleci/project/synchronization/trigger_test.go:29 +0x80
github.com/orbs-network/orbs-network-go/instrumentation/logfields.(*govnrErrorer).Error(0xc0001b4280, 0x8e2120, 0xc000011160)
	/home/circleci/project/instrumentation/logfields/govnr_error_handler.go:18 +0x204
github.com/orbs-network/govnr.recoverPanics(0x8e2000, 0xc0001b4280)
	/go/pkg/mod/github.com/orbs-network/govnr@v0.2.0/panic.go:24 +0xf3
panic(0x7d4b80, 0x8d9a50)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/orbs-network/orbs-network-go/synchronization_test.TestPeriodicalTriggerKeepsGoingOnPanic.func1.1()
	/home/circleci/project/synchronization/trigger_test.go:146 +0x40
github.com/orbs-network/orbs-network-go/synchronization.(*PeriodicalTrigger).run.func1()
	/home/circleci/project/synchronization/trigger.go:51 +0x5a
github.com/orbs-network/govnr.tryOnce(0x8e2000, 0xc0001b4280, 0xc0001c6140)
	/go/pkg/mod/github.com/orbs-network/govnr@v0.2.0/panic.go:19 +0x57
github.com/orbs-network/govnr.Forever.func1(0xc0001ba400, 0x8e2000, 0xc0001b4280, 0xc0001c6140, 0x8e9200, 0xc0001ba3c0)
	/go/pkg/mod/github.com/orbs-network/govnr@v0.2.0/forever.go:77 +0x69
created by github.com/orbs-network/govnr.Forever
	/go/pkg/mod/github.com/orbs-network/govnr@v0.2.0/forever.go:73 +0xfc
FAIL	github.com/orbs-network/orbs-network-go/synchronization	600.054s
+ exit 1
```

https://circleci.com/gh/orbs-network/orbs-network-go/19517

**Comment by ronnno** [comment]
issue occurs when the trigger fires (a third time) before `p.Stop()` gets a chance to run (scheduling race condition). In this case, the trigger handler will block because no one is reading from `<-logger.errors` which makes the trigger loop unresponsive to context cancellation. if the trigger handler is blocking when the context is cancelled the test will never end

**Comment by electricmonk** [comment]
duplicates #1282
