### ISSUE TITLE
Flakiness in acceptance - happens some times in acceptance count 100

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#233]
Can be seen here:

https://circleci.com/gh/orbs-network/orbs-network-go/1103?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
info 2018-09-19T23:57:11.935880Z waiting for transaction to be processed failed node=92d469 service=public-api error=timed out waiting for transaction result flow=checkpoint txHash=726539e368d500c158a086c597a137d4a2bb676691b9634e23cd4618bcef8d6d function=publicapi.(*service).SendTransaction source=services/publicapi/service.go:85 _test-id=acceptance-TestNonLeaderDeploysNativeContract-9078081893750708567-CONSENSUS_ALGO_TYPE_BENCHMARK_CONSENSUS 
info 2018-09-19T23:57:11.936249Z transaction status returned by public api node=92d469 service=public-api flow=checkpoint txHash=726539e368d500c158a086c597a137d4a2bb676691b9634e23cd4618bcef8d6d function=publicapi.(*service).SendTransaction source=services/publicapi/service.go:86 _test-id=acceptance-TestNonLeaderDeploysNativeContract-9078081893750708567-CONSENSUS_ALGO_TYPE_BENCHMARK_CONSENSUS 
panic: error sending counter deploy: timed out waiting for transaction result

goroutine 343985 [running]:
github.com/orbs-network/orbs-network-go/test/harness.(*inProcessNetwork).SendDeployCounterContract.func1(0xc479ad3c60, 0xc479ac8cd0, 0x1, 0xc479a252c0)
	/go/src/github.com/orbs-network/orbs-network-go/test/harness/network.go:203 +0x1d1
created by github.com/orbs-network/orbs-network-go/test/harness.(*inProcessNetwork).SendDeployCounterContract
	/go/src/github.com/orbs-network/orbs-network-go/test/harness/network.go:194 +0x386
FAIL	github.com/orbs-network/orbs-network-go/test/acceptance	177.538s
```

**Comment by electricmonk** [comment]
Happened again
https://circleci.com/gh/orbs-network/orbs-network-go/1145

**Comment by talkol** [comment]
We dealt with a lot of flakiness, reopen if this is still occuring
