### ISSUE TITLE
Block sync tests flakiness

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#323]
I've seen it just once and I'm not sure how severe it is.

```
panic: Mock call missing for LastCommittedBlockHeight()

goroutine 36 [running]:
github.com/orbs-network/orbs-network-go/vendor/github.com/orbs-network/go-mock.(*Mock).Called(0xc4201442d0, 0x0, 0x0, 0x0, 0x0)
	/Users/kirill/gopath/src/github.com/orbs-network/orbs-network-go/vendor/github.com/orbs-network/go-mock/mock.go:406 +0xf86
github.com/orbs-network/orbs-network-go/services/blockstorage/sync.(*blockSyncStorageMock).LastCommittedBlockHeight(0xc4201442d0, 0x48)
	/Users/kirill/gopath/src/github.com/orbs-network/orbs-network-go/services/blockstorage/sync/harness.go:22 +0x42
github.com/orbs-network/orbs-network-go/services/blockstorage/sync.(*collectingAvailabilityResponsesState).petitionerBroadcastBlockAvailabilityRequest(0xc42016c320, 0x1619cf8, 0xc42016c3c0)
	/Users/kirill/gopath/src/github.com/orbs-network/orbs-network-go/services/blockstorage/sync/state_collecting_availability_requests.go:68 +0x49
github.com/orbs-network/orbs-network-go/services/blockstorage/sync.(*collectingAvailabilityResponsesState).processState(0xc42016c320, 0x1412920, 0xc4201620c0, 0x0, 0x0)
	/Users/kirill/gopath/src/github.com/orbs-network/orbs-network-go/services/blockstorage/sync/state_collecting_availability_requests.go:34 +0xd6
github.com/orbs-network/orbs-network-go/services/blockstorage/sync.(*BlockSync).syncLoop(0xc420192000, 0x1412920, 0xc4201620c0)
	/Users/kirill/gopath/src/github.com/orbs-network/orbs-network-go/services/blockstorage/sync/block_sync.go:76 +0x330
created by github.com/orbs-network/orbs-network-go/services/blockstorage/sync.NewBlockSync
	/Users/kirill/gopath/src/github.com/orbs-network/orbs-network-go/services/blockstorage/sync/block_sync.go:68 +0x52f
FAIL	github.com/orbs-network/orbs-network-go/services/blockstorage/sync	0.040s
```

**Comment by jlevison** [comment]
it was caused by a weird pause of 4.5ms of the test main loop (system did not freeze or if it did the sync thread got cpu time) - thinking about how to resolve this, will update

**Comment by netoneko** [comment]
Another flakiness (or maybe the same one?) in block sync:

```
--- FAIL: TestIdleStateStaysIdleOnCommit (0.00s)
	require.go:687: 
			Error Trace:	state_idle_test.go:18
			Error:      	Object expected to be of type *sync.idleState, but was *sync.collectingAvailabilityResponsesState
			Test:       	TestIdleStateStaysIdleOnCommit
			Messages:   	next should still be idle
```
