### ISSUE TITLE
Flakiness in block sync

### ISSUE THREAD

**Issue by netoneko** [orbs-network/orbs-network-go#362]
```
--- FAIL: TestWaitingAcceptsNewBlockAndMovesToProcessing (0.03s)
	require.go:687: 
			Error Trace:	state_waiting_for_chunks_test.go:55
			Error:      	Object expected to be of type *sync.processingBlocksState, but was *sync.idleState
			Test:       	TestWaitingAcceptsNewBlockAndMovesToProcessing
			Messages:   	expecting to be at processing state after blocks arrived
```

https://circleci.com/gh/orbs-network/orbs-network-go/2383?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by jlevison** [comment]
i couldn't reproduce this at count=10000 :/ but there may be a timing issue there as it is yielding without a latch, will try to think of a way to add a latch

**Comment by netoneko** [comment]
Another one:

```
panic: Mock call missing for:
BroadcastBlockAvailabilityRequest([context.Background.WithCancel {Message:{SignedBatchRange:{BlockType:BLOCK_TYPE_BLOCK_PAIR,FirstBlockHeight:1,LastBlockHeight:2,LastCommittedBlockHeight:0,},Sender:{SenderPublicKey:dfc06c5be24a67adee80b35ab4f147bb1a35c55ff85eda69f40ef827bddec173,Signature:,},},}])
Expected calls:



goroutine 26 [running]:
github.com/orbs-network/orbs-network-go/vendor/github.com/orbs-network/go-mock.(*Mock).Called(0xc42016d500, 0xc4200f3500, 0x2, 0x2, 0x0)
	/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/orbs-network/go-mock/mock.go:406 +0xf86
github.com/orbs-network/orbs-network-go/vendor/github.com/orbs-network/orbs-spec/types/go/services/gossiptopics.(*MockBlockSync).BroadcastBlockAvailabilityRequest(0xc42016d500, 0x83ec40, 0xc42011fcc0, 0xc42000e280, 0x2, 0x2, 0xc420043d50)
	/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/orbs-network/orbs-spec/types/go/services/gossiptopics/block_sync_mock.mb.go:17 +0xb9
github.com/orbs-network/orbs-network-go/services/blockstorage/sync.(*blockSyncGossipClient).petitionerBroadcastBlockAvailabilityRequest(0xc42005f040, 0x83ec40, 0xc42011fcc0, 0xc420043f08, 0x1)
	/go/src/github.com/orbs-network/orbs-network-go/services/blockstorage/sync/block_sync_gossip_client.go:67 +0x315
github.com/orbs-network/orbs-network-go/services/blockstorage/sync.(*collectingAvailabilityResponsesState).processState(0xc420011c20, 0x83ec40, 0xc42011fcc0, 0xc42000e268, 0x1)
	/go/src/github.com/orbs-network/orbs-network-go/services/blockstorage/sync/state_collecting_availability_requests.go:31 +0xad
github.com/orbs-network/orbs-network-go/services/blockstorage/sync.(*BlockSync).syncLoop(0xc42016fc80, 0x83ec40, 0xc42011fcc0)
	/go/src/github.com/orbs-network/orbs-network-go/services/blockstorage/sync/block_sync.go:71 +0x162
created by github.com/orbs-network/orbs-network-go/services/blockstorage/sync.NewBlockSync
	/go/src/github.com/orbs-network/orbs-network-go/services/blockstorage/sync/block_sync.go:63 +0x4e9
```
https://circleci.com/gh/orbs-network/orbs-network-go/2387
