### ISSUE TITLE
Mock call missing when running tests with count of more than 50 times in Gossip Adapter

### ISSUE THREAD

**Issue by itamararjuan** [orbs-network/orbs-network-go#375]
info 2018-10-28T12:47:54.964974Z block sync init flow=block-sync no-commit-timeout=30s collect-responses-timeout=5ms collect-chunks-timeout=20ms batch-size=2 function=sync.NewBlockSync source=services/blockstorage/sync/block_sync.go:57
info 2018-10-28T12:47:54.965012Z state transitioning flow=block-sync current-state=collecting-availability-responses function=sync.(*BlockSync).syncLoop source=services/blockstorage/sync/block_sync.go:69
info 2018-10-28T12:47:54.965026Z broadcast block availability request first-block-height=1 last-block-height=2 function=sync.(*blockSyncGossipClient).petitionerBroadcastBlockAvailabilityRequest source=services/blockstorage/sync/block_sync_gossip_client.go:49
panic: Mock call missing for:
BroadcastBlockAvailabilityRequest([context.Background.WithCancel {Message:{SignedBatchRange:{BlockType:BLOCK_TYPE_BLOCK_PAIR,FirstBlockHeight:1,LastBlockHeight:2,LastCommittedBlockHeight:0,},Sender:{SenderPublicKey:dfc06c5be24a67adee80b35ab4f147bb1a35c55ff85eda69f40ef827bddec173,Signature:,},},}])
Expected calls:

goroutine 231 [running]:
github.com/orbs-network/orbs-network-go/vendor/github.com/orbs-network/go-mock.(*Mock).Called(0xc4203fb860, 0xc42017e740, 0x2, 0x2, 0x0)
	/Users/itamar/dev/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/orbs-network/go-mock/mock.go:406 +0xf86
github.com/orbs-network/orbs-network-go/vendor/github.com/orbs-network/orbs-spec/types/go/services/gossiptopics.(*MockBlockSync).BroadcastBlockAvailabilityRequest(0xc4203fb860, 0x143f900, 0xc4202e6540, 0xc42033a590, 0x2, 0x2, 0xc420305d50)
	/Users/itamar/dev/go/src/github.com/orbs-network/orbs-network-go/vendor/github.com/orbs-network/orbs-spec/types/go/services/gossiptopics/block_sync_mock.mb.go:17 +0xb9
github.com/orbs-network/orbs-network-go/services/blockstorage/sync.(*blockSyncGossipClient).petitionerBroadcastBlockAvailabilityRequest(0xc4202f7740, 0x143f900, 0xc4202e6540, 0xc420305f08, 0x1)
	/Users/itamar/dev/go/src/github.com/orbs-network/orbs-network-go/services/blockstorage/sync/block_sync_gossip_client.go:67 +0x315
github.com/orbs-network/orbs-network-go/services/blockstorage/sync.(*collectingAvailabilityResponsesState).processState(0xc4203ae090, 0x143f900, 0xc4202e6540, 0xc42033a578, 0x1)
	/Users/itamar/dev/go/src/github.com/orbs-network/orbs-network-go/services/blockstorage/sync/state_collecting_availability_requests.go:31 +0xad
github.com/orbs-network/orbs-network-go/services/blockstorage/sync.(*BlockSync).syncLoop(0xc420376840, 0x143f900, 0xc4202e6540)
	/Users/itamar/dev/go/src/github.com/orbs-network/orbs-network-go/services/blockstorage/sync/block_sync.go:71 +0x162
created by github.com/orbs-network/orbs-network-go/services/blockstorage/sync.NewBlockSync
	/Users/itamar/dev/go/src/github.com/orbs-network/orbs-network-go/services/blockstorage/sync/block_sync.go:63 +0x4e9

**Comment by electricmonk** [comment]
isn't this the block sync flakiness? @jlevison was it solved?
