### ISSUE TITLE
Flakiness: timed out waiting for transaction in stress test

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-network-go#399]
https://circleci.com/gh/orbs-network/orbs-network-go/2731

```
orbs-acceptance_1  | 
orbs-acceptance_1  | --- FAIL: TestCreateGazillionTransactionsWhileTransportIsDelayingRandomMessages (1.06s)
orbs-acceptance_1  | panic: timed out waiting for transaction with hash 6b4bcb17c3f0ef4680c6f47cd43dcea63c094425f9c26ca1b37614e2c7793e52 [recovered]
orbs-acceptance_1  | 	panic: timed out waiting for transaction with hash 6b4bcb17c3f0ef4680c6f47cd43dcea63c094425f9c26ca1b37614e2c7793e52
orbs-acceptance_1  | 
orbs-acceptance_1  | goroutine 12505 [running]:
orbs-acceptance_1  | testing.tRunner.func1(0xc42050c690)
orbs-acceptance_1  | 	/usr/local/go/src/testing/testing.go:742 +0x29d
orbs-acceptance_1  | panic(0x98a680, 0xc420152d30)
orbs-acceptance_1  | 	/usr/local/go/src/runtime/panic.go:502 +0x229
orbs-acceptance_1  | github.com/orbs-network/orbs-network-go/test/harness/services/blockstorage/adapter.(*inMemoryBlockPersistence).WaitForTransaction(0xc4204740c0, 0xa8bd00, 0xc420474000, 0xc420694ba0, 0x20, 0x20, 0x3b9aca00, 0xc420695c00)
orbs-acceptance_1  | 	/go/src/github.com/orbs-network/orbs-network-go/test/harness/services/blockstorage/adapter/memory_persistence.go:59 +0x384
orbs-acceptance_1  | github.com/orbs-network/orbs-network-go/test/harness.(*inProcessNetwork).WaitForTransactionInStateForAtMost(0xc420326c30, 0xa8bd00, 0xc420474000, 0x0, 0xc420694ba0, 0x20, 0x20, 0x3b9aca00)
orbs-acceptance_1  | 	/go/src/github.com/orbs-network/orbs-network-go/test/harness/network.go:87 +0xb3
orbs-acceptance_1  | github.com/orbs-network/orbs-network-go/test/harness.(*inProcessNetwork).WaitForTransactionInState(0xc420326c30, 0xa8bd00, 0xc420474000, 0x0, 0xc420694ba0, 0x20, 0x20)
orbs-acceptance_1  | 	/go/src/github.com/orbs-network/orbs-network-go/test/harness/network.go:83 +0x73
orbs-acceptance_1  | github.com/orbs-network/orbs-network-go/test/acceptance.sendTransfersAndAssertTotalBalance(0xa8bd00, 0xc420474000, 0xa8e1c0, 0xc420326c30, 0xc42050c690, 0x64)
```

doesn't look like a deadlock from the logs

**Comment by talkol** [comment]
There is another issue with block storage mutexes that will be mitigated by solving https://github.com/orbs-network/orbs-network-go/issues/398

**Comment by talkol** [comment]
Opened because this is not resolved yet

**Comment by electricmonk** [comment]
another: https://circleci.com/gh/orbs-network/orbs-network-go/3130?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by electricmonk** [comment]
@talkol handled in #474 ?
