### ISSUE TITLE
flakiness in inter node block sync in service sync acceptance test

### ISSUE THREAD

**Issue by ronnno** [orbs-network/orbs-network-go#516]
triggered by TestInternalBlockSync_StateStorage
This test starts two networks and waits until state is synced first by inter-node sync and then by service sync. the break appears to be in the inter-node sync phase
```
--- FAIL: TestInternalBlockSync_StateStorage (0.39s)
	testify_extensions.go:41: Encountered unexpected errors:
			 failed to validate block received via sync (passed Error object: block height is 10, expected 11)
```
see:
https://circleci.com/gh/orbs-network/orbs-network-go/4121?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ronnno** [comment]
and another one. this one triggered by `TestCreateGazillionTransactionsWhileTransportIsCorruptingRandomMessages`:

```
info 2018-11-21T16:55:25.388385Z transport message received node=a899b3 service=gossip entry-point=BlockSync request-id=BlockSync-1542819325387393758 header={ProtocolVersion:0,VirtualChainId:0,RecipientPublicKeys:[],RecipientMode:RECIPIENT_LIST_MODE_BROADCAST,Topic:(BlockSync)BLOCK_SYNC_AVAILABILITY_REQUEST,} function=gossip.(*service).OnTransportMessageReceived source=services/gossip/service.go:51 _test=acceptance _branch= _commit= _test-id=acceptance-TestCreateGazillionTransactionsWhileTransportIsCorruptingRandomMessages-1542819325-CONSENSUS_ALGO_TYPE_BENCHMARK_CONSENSUS
info 2018-11-21T16:55:25.388449Z transport message received node=a899b3 service=gossip entry-point=BlockSync request-id=BlockSync-1542819325387742041 header={ProtocolVersion:0,VirtualChainId:0,RecipientPublicKeys:[],RecipientMode:RECIPIENT_LIST_MODE_BROADCAST,Topic:(BlockSync)BLOCK_SYNC_AVAILABILITY_REQUEST,} function=gossip.(*service).OnTransportMessageReceived source=services/gossip/service.go:51 _test=acceptance _branch= _commit= _test-id=acceptance-TestCreateGazillionTransactionsWhileTransportIsCorruptingRandomMessages-1542819325-CONSENSUS_ALGO_TYPE_BENCHMARK_CONSENSUS
info 2018-11-21T16:55:25.388720Z block sync init node=a899b3 service=block-storage flow=block-sync no-commit-timeout=100ms collect-responses-timeout=15ms collect-chunks-timeout=15ms batch-size=5 function=internodesync.newBlockSyncWithFactory source=services/blockstorage/internodesync/block_sync.go:87 _test=acceptance _branch= _commit= _test-id=acceptance-TestCreateGazillionTransactionsWhileTransportIsCorruptingRandomMessages-1542819325-CONSENSUS_ALGO_TYPE_BENCHMARK_CONSENSUS
error 2018-11-21T16:55:25.388788Z recovered panic peer-listener=����Y�-�(A�/�ݭ�Ks�
                                                                                  ���G��� error=goroutine panicked at [github.com/orbs-network/orbs-network-go/services/blockstorage.(*service).sourceHandleBlockAvailabilityRequest:25]: runtime error: invalid memory address or nil pointer dereference stack-trace=goroutine 4114 [running]:
runtime/debug.Stack(0x44e74a0, 0xc42054e0a0, 0xc420306090)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/orbs-network/orbs-network-go/synchronization/supervised.recoverPanics(0x4972120, 0xc4204fd0e0)
	/Users/ron/work/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/recover.go:14 +0x138
panic(0x4412660, 0x472bf00)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/orbs-network/orbs-network-go/services/blockstorage.(*service).sourceHandleBlockAvailabilityRequest(0x0, 0x44ee4c0, 0xc4203081e0, 0xc42012af80, 0xf8, 0xf9)
	/Users/ron/work/src/github.com/orbs-network/orbs-network-go/services/blockstorage/block_sync_server.go:25 +0x93
github.com/orbs-network/orbs-network-go/services/blockstorage.(*service).HandleBlockAvailabilityRequest(0x0, 0x44ee4c0, 0xc4203081e0, 0xc42000e608, 0x3, 0x4733670, 0xc42000aac0)
	/Users/ron/work/src/github.com/orbs-network/orbs-network-go/services/blockstorage/block_sync_server.go:15 +0x4c
github.com/orbs-network/orbs-network-go/services/gossip.(*service).receivedBlockSyncAvailabilityRequest(0xc420169560, 0x44ee4c0, 0xc4203081e0, 0xc42034f6e0, 0xc42009f698, 0x2, 0x2)
	/Users/ron/work/src/github.com/orbs-network/orbs-network-go/services/gossip/topic_block_sync.go:61 +0x302
github.com/orbs-network/orbs-network-go/services/gossip.(*service).receivedBlockSyncMessage(0xc420169560, 0x44ee4c0, 0xc4203081e0, 0xc42034f6e0, 0xc42009f698, 0x2, 0x2)
	/Users/ron/work/src/github.com/orbs-network/orbs-network-go/services/gossip/topic_block_sync.go:20 +0xea
github.com/orbs-network/orbs-network-go/services/gossip.(*service).OnTransportMessageReceived(0xc420169560, 0x44ee4c0, 0xc4203081e0, 0xc42009f680, 0x3, 0x3)
	/Users/ron/work/src/github.com/orbs-network/orbs-network-go/services/gossip/service.go:60 +0x390
github.com/orbs-network/orbs-network-go/services/gossip/adapter.receive(0x44ee400, 0xc42060c800, 0x44e7220, 0xc420169560, 0xc42009f680, 0x3, 0x3, 0xc4204d01c0)
	/Users/ron/work/src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/memory_transport.go:118 +0x106
github.com/orbs-network/orbs-network-go/services/gossip/adapter.(*peer).acceptUsing(0xc42012a810, 0x44ee400, 0xc42060c800, 0x44e7220, 0xc420169560)
	/Users/ron/work/src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/memory_transport.go:107 +0x91
github.com/orbs-network/orbs-network-go/services/gossip/adapter.newPeer.func1()
	/Users/ron/work/src/github.com/orbs-network/orbs-network-go/services/gossip/adapter/memory_transport.go:81 +0x158
github.com/orbs-network/orbs-network-go/synchronization/supervised.tryOnce(0x4972120, 0xc4204fd0e0, 0xc42051af20)
	/Users/ron/work/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:46 +0x57
github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever.func1(0xc420530f00, 0x4972120, 0xc4204fd0e0, 0xc42051af20, 0x44ee400, 0xc42060c800)
	/Users/ron/work/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:33 +0x69
created by github.com/orbs-network/orbs-network-go/synchronization/supervised.GoForever
	/Users/ron/work/src/github.com/orbs-network/orbs-network-go/synchronization/supervised/supervisor.go:29 +0x8e
 function=supervised.recoverPanics source=synchronization/supervised/recover.go:14 _test=acceptance _branch= _commit= _test-id=acceptance-TestCreateGazillionTransactionsWhileTransportIsCorruptingRandomMessages-1542819325-CONSENSUS_ALGO_TYPE_BENCHMARK_CONSENSUS
info 2018-11-21T16:55:25.388796Z state transitioning node=a899b3 service=block-storage flow=block-sync current-state=collecting-availability-responses entry-point=BlockSync request-id=BlockSync-1542819325388772677 function=internodesync.(*BlockSync).syncLoop source=services/blockstorage/internodesync/block_sync.go:122 _test=acceptance _branch= _commit= _test-id=acceptance-TestCreateGazillionTransactionsWhileTransportIsCorruptingRandomMessages-1542819325-CONSENSUS_ALGO_TYPE_BENCHMARK_CONSENSUS
info 2018-11-21T16:55:25.388814Z Node started node=a899b3 function=bootstrap.NewNodeLogic source=bootstrap/node_logic.go:78 _test=acceptance _branch= _commit= _test-id=acceptance-TestCreateGazillionTransactionsWhileTransportIsCorruptingRandomMessages-1542819325-CONSENSUS_ALGO_TYPE_BENCHMARK_CONSENSUS
info 2018-11-21T16:55:25.388820Z broadcast block availability request node=a899b3 service=block-storage flow=block-sync entry-point=BlockSync request-id=BlockSync-1542819325388772677 first-block-height=1 last-block-height=5 function=internodesync.(*blockSyncGossipClient).petitionerBroadcastBlockAvailabilityRequest source=services/blockstorage/internodesync/block_sync_gossip_client.go:58 _test=acceptance _branch= _commit= _test-id=acceptance-TestCreateGazillionTransactionsWhileTransportIsCorruptingRandomMessages-1542819325-CONSENSUS_ALGO_TYPE_BENCHMARK_CONSENSUS
info 2018-11-21T16:55:25.388864Z state dump node=0 data={height: 0, data: {}} function=harness.(*acceptanceNetwork).DumpState source=test/harness/acceptance_network.go:59 _test=acceptance _branch= _commit= _test-id=acceptance-TestCreateGazillionTransactionsWhileTransportIsCorruptingRandomMessages-1542819325-CONSENSUS_ALGO_TYPE_BENCHMARK_CONSENSUS
info 2018-11-21T16:55:25.388875Z transport message received node=dfc06c service=gossip entry-point=BlockSync request-id=BlockSync-1542819325388772677 header={ProtocolVersion:0,VirtualChainId:0,RecipientPublicKeys:[],RecipientMode:RECIPIENT_LIST_MODE_BROADCAST,Topic:(BlockSync)BLOCK_SYNC_AVAILABILITY_REQUEST,} function=gossip.(*service).OnTransportMessageReceived source=services/gossip/service.go:51 _test=acceptance _branch= _commit= _test-id=acceptance-TestCreateGazillionTransactionsWhileTransportIsCorruptingRandomMessages-1542819325-CONSENSUS_ALGO_TYPE_BENCHMARK_CONSENSUS
info 2018-11-21T16:55:25.388880Z state dump node=1 data={height: 0, data: {}} function=harness.(*acceptanceNetwork).DumpState source=test/harness/acceptance_network.go:59 _test=acceptance _branch= _commit= _test-id=acceptance-TestCreateGazillionTransactionsWhileTransportIsCorruptingRandomMessages-1542819325-CONSENSUS_ALGO_TYPE_BENCHMARK_CONSENSUS
info 2018-11-21T16:55:25.388892Z state dump node=2 data={height: 0, data: {}} function=harness.(*acceptanceNetwork).DumpState source=test/harness/acceptance_network.go:59 _test=acceptance _branch= _commit= _test-id=acceptance-TestCreateGazillionTransactionsWhileTransportIsCorruptingRandomMessages-1542819325-CONSENSUS_ALGO_TYPE_BENCHMARK_CONSENSUS
info 2018-11-21T16:55:25.388896Z received block availability request node=dfc06c service=block-storage entry-point=BlockSync request-id=BlockSync-1542819325388772677 petitioner=a899b318e65915aa2de02841eeb72fe51fddad96014b73800ca788a547f8cce0 requested-first-block=1 requested-last-block=5 requested-last-committed-block=0 function=blockstorage.(*service).sourceHandleBlockAvailabilityRequest source=services/blockstorage/block_sync_server.go:27 _test=acceptance _branch= _commit= _test-id=acceptance-TestCreateGazillionTransactionsWhileTransportIsCorruptingRandomMessages-1542819325-CONSENSUS_ALGO_TYPE_BENCHMARK_CONSENSUS
info 2018-11-21T16:55:25.388897Z replying committed with last committed height node=92d469 service=consensus-algo-benchmark entry-point=BenchmarkConsensus.Tick request-id=BenchmarkConsensus.Tick-1542819325387718695 block-height=0 signed-data=af5570f5a1810b7af78caf4bc70a660f0df51e42baf91d4de5b2328de0e83dfc function=benchmarkconsensus.(*service).nonLeaderCommitAndReply source=services/consensusalgo/benchmarkconsensus/non_leader.go:96 _test=acceptance _branch= _commit= _test-id=acceptance-TestCreateGazillionTransactionsWhileTransportIsCorruptingRandomMessages-1542819325-CONSENSUS_ALGO_TYPE_BENCHMARK_CONSENSUS
FAIL search snippet: grep _test-id=acceptance-TestCreateGazillionTransactionsWhileTransportIsCorruptingRandomMessages-1542819325-CONSENSUS_ALGO_TYPE_BENCHMARK_CONSENSUS test.out
info 2018-11-21T16:55:25.388940Z transport message received node=92d469 service=gossip entry-point=BlockSync request-id=BlockSync-1542819325388772677 header={ProtocolVersion:0,VirtualChainId:0,RecipientPublicKeys:[],RecipientMode:RECIPIENT_LIST_MODE_BROADCAST,Topic:(BlockSync)BLOCK_SYNC_AVAILABILITY_REQUEST,} function=gossip.(*service).OnTransportMessageReceived source=services/gossip/service.go:51 _test=acceptance _branch= _commit= _test-id=acceptance-TestCreateGazillionTransactionsWhileTransportIsCorruptingRandomMessages-1542819325-CONSENSUS_ALGO_TYPE_BENCHMARK_CONSENSUS
--- FAIL: TestCreateGazillionTransactionsWhileTransportIsCorruptingRandomMessages (0.00s)
	stress_test.go:56: this test causes the system to hang, seems like consensus algo stops
	testify_extensions.go:41: Encountered unexpected errors:
			 recovered panic (passed Error object: goroutine panicked at [github.com/orbs-network/orbs-network-go/services/blockstorage.(*service).sourceHandleBlockAvailabilityRequest:25]: runtime error: invalid memory address or nil pointer dereference)
info 2018-11-21T16:55:25.388959Z received block availability request node=92d469 service=block-storage entry-point=BlockSync request-id=BlockSync-1542819325388772677 petitioner=a899b318e65915aa2de02841eeb72fe51fddad96014b73800ca788a547f8cce0 requested-first-block=1 requested-last-block=5 requested-last-committed-block=0 function=blockstorage.(*service).sourceHandleBlockAvailabilityRequest source=services/blockstorage/block_sync_server.go:27 _test=acceptance _branch= _commit= _test-id=acceptance-TestCreateGazillionTransactionsWhileTransportIsCorruptingRandomMessages-1542819325-CONSENSUS_ALGO_TYPE_BENCHMARK_CONSENSUS
FAIL
```

**Comment by ronnno** [comment]
The first issue:  `failed to validate block received via sync (passed Error object: block height is 10, expected 11)` appears to be a result of a normal condition where the block sync races with consensus algo to present blocks of same height. if the blocks are identical this should not raise an error.

**Comment by ronnno** [comment]
Fixed by allowing past blocks in the validation phase and adding a check in the BlockStorage adapter, under lock, to ignore past block heights and avoid notification of other services
