### ISSUE TITLE
TestBulkOutput_Append test flaky

### ISSUE THREAD

**Issue by jlevison** [orbs-network/orbs-network-go#832]
see: https://circleci.com/gh/orbs-network/orbs-network-go/8328#artifacts/containers/0

```
=== RUN   TestBulkOutput_Append
2019-02-04 12:58:53.890585876 +0000 UTC m=+0.041164321 failed to send logs via http, 0 bytes lost: Failed to send logs: Post http://127.0.0.1:0/submit-logs: dial tcp 127.0.0.1:0: connect: connection refused
panic: test timed out after 7m0s

goroutine 23 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1296 +0xfd
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000136300, 0x8584fa, 0x15, 0x86cd10, 0x47c301)
	/usr/local/go/src/testing/testing.go:879 +0x383
testing.runTests.func1(0xc000136000)
	/usr/local/go/src/testing/testing.go:1119 +0x78
testing.tRunner(0xc000136000, 0xc0000d3e08)
	/usr/local/go/src/testing/testing.go:827 +0xbf
testing.runTests(0xc00000c840, 0xd48da0, 0x17, 0x17, 0x40e16f)
	/usr/local/go/src/testing/testing.go:1117 +0x2aa
testing.(*M).Run(0xc000134000, 0x0)
	/usr/local/go/src/testing/testing.go:1034 +0x165
main.main()
	_testmain.go:92 +0x13d

goroutine 12 [semacquire]:
sync.runtime_Semacquire(0xc00001a758)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc00001a750)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/orbs-network/orbs-network-go/instrumentation/log.TestBulkOutput_Append(0xc000136300)
	/go/src/github.com/orbs-network/orbs-network-go/instrumentation/log/bulk_output_test.go:116 +0x33a
testing.tRunner(0xc000136300, 0x86cd10)
	/usr/local/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x35c

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x7ffae5aadf60, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000134098, 0x72, 0xc000010800, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000134098, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc000134080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1a0
net.(*netFD).accept(0xc000134080, 0xc000152050, 0xab57fd9037aacd1f, 0x44d6f8)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc00000e060, 0x5c58370d, 0xc00008fe20, 0x47c376)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x2e
net.(*TCPListener).Accept(0xc00000e060, 0xc00008fe70, 0x18, 0xc000001c80, 0x6bf385)
	/usr/local/go/src/net/tcpsock.go:260 +0x47
net/http.(*Server).Serve(0xc0000bb1e0, 0x8bf240, 0xc00000e060, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2826 +0x22f
github.com/orbs-network/orbs-network-go/instrumentation/log.(*httpOutputHarness).start.func1(0xc000136100, 0xc0000b9200)
	/go/src/github.com/orbs-network/orbs-network-go/instrumentation/log/bulk_output_test.go:45 +0x242
created by github.com/orbs-network/orbs-network-go/instrumentation/log.(*httpOutputHarness).start
	/go/src/github.com/orbs-network/orbs-network-go/instrumentation/log/bulk_output_test.go:33 +0x49

goroutine 13 [IO wait]:
internal/poll.runtime_pollWait(0x7ffae5aadcf0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000134398, 0x72, 0xc000010900, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000134398, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc000134380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1a0
net.(*netFD).accept(0xc000134380, 0x7ffae5b09000, 0x0, 0xc0001c0e18)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc00000e0a0, 0xc0001c0e20, 0x40e9f8, 0x30)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x2e
net.(*TCPListener).Accept(0xc00000e0a0, 0x825120, 0xc0000b9bc0, 0x7e0fe0, 0xd40c40)
	/usr/local/go/src/net/tcpsock.go:260 +0x47
net/http.(*Server).Serve(0xc0000bb450, 0x8bf240, 0xc00000e0a0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2826 +0x22f
github.com/orbs-network/orbs-network-go/instrumentation/log.(*httpOutputHarness).start.func1(0xc000136300, 0xc0000b9a10)
	/go/src/github.com/orbs-network/orbs-network-go/instrumentation/log/bulk_output_test.go:45 +0x242
created by github.com/orbs-network/orbs-network-go/instrumentation/log.(*httpOutputHarness).start
	/go/src/github.com/orbs-network/orbs-network-go/instrumentation/log/bulk_output_test.go:33 +0x49
FAIL	github.com/orbs-network/orbs-network-go/instrumentation/log	420.031s
```

**Comment by jlevison** [comment]
logger extracted, not sure if this was handled or not but its irrelevant here
